[package]
name = "serde-bolt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.101"
serde_bytes = "0.11.2"
serde_derive = "1.0.101"

[dev-dependencies]
